### ISSUE TITLE
Order of selection is wrong

### ISSUE THREAD

**Issue by DipakCapermint** [mikaoj/BSImagePicker#193]
I am using this library in my every project and this is the perfect one for all kind of user. 
The problem is when selecting multiple images, let's say 5 or 6 than order images loads into collectionview or table is not same as order of selected images. It is always random. Is there any way I can manage? 

Thanks.

**Comment by mikaoj** [comment]
I'm not sure if I understand...
If you have a collection of images: 1, 2, 3, 4, 5, 6, 8
And you select: 6, 1 and 8

You want the selected images be ordered as: 1, 6 and 8?

**Comment by KLinh** [comment]
> I'm not sure if I understand...
> If you have a collection of images: 1, 2, 3, 4, 5, 6, 8
> And you select: 6, 1 and 8
> 
> You want the selected images be ordered as: 1, 6 and 8?


Yes, I had the same issue. Could you provide the solution for this?

**Comment by BadReese** [comment]
same to them.
Could you provide the solution for this?
@mikaoj

**Comment by mikaoj** [comment]
I believe that _most_ users would like them ordered in the order they where selected.
But you could easily sort them yourself, every PHAsset has a creationDate which is what they are ordered after in BSImagePicker.
So just sort them by that in the finish closure.

**Comment by BadReese** [comment]
@mikaoj 
I am sorry that i misunderstanding DipakCapermint's issue,
I agree with you that most users would like them ordered in the order they where selected.

**Comment by mikaoj** [comment]
So what was your issue then? :)

**Comment by BadReese** [comment]
I want to confirm that If user choose images by order of [0, 2, 1] and close BSImagePickerViewController, next time I send these images to BSImagePickerViewController for user to keep picking images, BSImagePickerViewController will keep same order of [0, 2, 1],because user just choose this order , right ?

If so, my issue is from another resp of flutter
this is the link [https://github.com/Sh1d0w/multi_image_picker/issues/253](url)

**Comment by BadReese** [comment]
@mikaoj I am sorry for that my English is pool,  please forgive me if I offend you in tone.
