### ISSUE TITLE
iCloud photos will display white block when picker images

### ISSUE THREAD

**Issue by chenft** [mikaoj/BSImagePicker#213]
**Describe the bug**

**To Reproduce**
When people select photos, iCloud's photos will display like a white block.But after selectd, it will display a really photo in AssetThumb.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
![1559191218971](https://user-images.githubusercontent.com/17562266/58608873-1ea22380-82d8-11e9-92a4-9af67d8180ca.jpg)

**BSImagePicker configuration**
Add your configuration/settings here.

**Comment by malikdoksoz** [comment]
Has this problem been solved?

**Comment by mikaoj** [comment]
It's quite easy to fix. I'll try to find the time to do it this weeked.
Setting isNetworkAccessAllowed to true on PHImageRequestOptions should do it.

Or if any of you beat me to it with a pull-request I would be happy to review it ^^

**Comment by danfordham** [comment]
Hi Joakim, I did try setting that last night, and then tried lots of different options to get it working, but I had no luck. Will have another look at it tonight, thanks.

**Comment by mikaoj** [comment]
Theres a bunch of places where PHImageRequestOptions isn't used and nil is sent instead.
For the list it would be here (PhotoCollectionViewDataSource):

        // Request image
        cell.tag = Int(photosManager.requestImage(for: asset, targetSize: imageSize, contentMode: imageContentMode, options: nil) { (result, _) in
            cell.imageView.image = result
        })
But there should be a couple of more places, like preview and album/collections.

You would need to find all those, create a PHImageRequestOption object and set isNetworkAccessAllowed to true, and pass that instead of nil.

That _should_ work. If not I'm not sure whats wrong ¯\_(ツ)_/¯

**Comment by mikaoj** [comment]
Can you test branch bugfix/fetch_images_from_icloud and see if that works?

**Comment by mikaoj** [comment]
I can't reproduce the bug myself. So I would need some help with testing.

I think images are kept on device as long as there are plenty of storage - so that why I can't reproduce it :)

**Comment by mikaoj** [comment]
If you want to test it in your app and are using cocoapods you can point it to a specific branch using
pod 'BSImagePicker', :git => 'https://github.com/mikaoj/BSImagePicker.git', :branch => 'bugfix/fetch_images_from_icloud'

There is also an example app in this repo that could be used for testing.

**Comment by danfordham** [comment]
I've tested that branch this morning and I couldn't get it working, so I'm now looking at version 2.9.0, which is working, to try and work it out.

In the bugfix branch the new image options aren't being used in the actual request, in PhotoCollectionViewDataSource, so I've corrected that locally. 

One thing I have noticed is that the target imageSize is very big, it's coming in at 3339x3339px on my XS. In version 2.9.0 the target size is 123.66x123.66px, which is working but causing the images to look quite blurry.

I did try using target sizes of 100x100px and 500x500px in the bugfix branch, before switching back to 2.9.0, but it still fails to load some of the images.

**Comment by danfordham** [comment]
My iPhone's (iCloud -> Photos) settings have the following setup:
- Optimise iPhone Storage: true
- Download and Keep Originals: false

**Comment by mikaoj** [comment]
Hmm...yeah 3339x3339 sounds way to large for the list
In the image fetch result handler there is a dictionary that could contain errors. Could you check it?

```
        cell.tag = Int(photosManager.requestImage(for: asset, targetSize: imageSize, contentMode: imageContentMode, options: imageRequestOptions) { (result, info) in
            print(info)
            print("Error: \(info?[PHImageErrorKey])")
            cell.imageView.image = result
        })
```

**Comment by mikaoj** [comment]
I think I fixed the issue with imageSize being too large.

**Comment by danfordham** [comment]
I've fixed the blank cells issue, looks like it was a race condition problem, as a cancelled request on a re-used cell would trigger the completion block and set the image on the cell to nil. There was also an issue where if you scrolled through a large album too quickly, the cell images would visibly change as they came in, as the previous image wasn't cleared.

I've also fixed an issue with the album title not growing in size for longer album titles. I fixed it to size correctly, but the existing edgeInsets approach, to swap the title and image position then didn't work, as the title frame (width) is dynamic and not certain due to the room available in the navigation bar. So the button now has a changed horizontal order, seems to work well.

Is it possible for me to push my commits to that branch? I get a 403 when attempting it. Thanks!

**Comment by mikaoj** [comment]
Cool, looking forward to seeing the code 🥇 

Fork this repo (which I believe you've already did), commit your fixes and push to your fork.
Then you create a pull request from your fork to this repo.

**Comment by mikaoj** [comment]
I've pushed 2.10.2 which should fix this issue.
Thanks @danfordham ! :)

**Comment by danfordham** [comment]
Am glad I could contribute, it's a great library, thanks @mikaoj !
