### ISSUE TITLE
Uncategorized: Command CompileSwift failed with a nonzero exit code

### ISSUE THREAD

**Issue by dks333** [mikaoj/BSImagePicker#217]
<img width="318" alt="Screen Shot 2019-08-09 at 4 47 29 PM" src="https://user-images.githubusercontent.com/52273168/62814467-d9fbeb00-bac5-11e9-8e2f-89dd7e4805a5.png">
Any advice on solving this issue?

Swift 5.0
Xcode 10.3
BSImagePicker 2.10

**Comment by EHBradford** [comment]
Having this issue as well.

**Comment by mikaoj** [comment]
Use 2.10.2 and Xcode 11

**Comment by robert4381** [comment]
Same issue with this configuration.

> Use 2.10.2 and Xcode 11

`
/Users/ralmeida/Proyectos/iubo/source_app/Carthage/Checkouts/BSImagePicker/Sources/Controller/PhotosViewController.swift:25:8: error: module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/ralmeida/Proyectos/iubo/source_app/Carthage/Checkouts/BSImagePicker/Frameworks/BSGridCollectionViewLayout.framework/Modules/BSGridCollectionViewLayout.swiftmodule/arm64.swiftmodule
import BSGridCollectionViewLayout
       ^

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
`

**Comment by EHBradford** [comment]
I too am fully up to date on Xcode 11 and 2.10.2  and I receive exactly same error as robert4381:

<unknown>:0: error: module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/bob/Library/Developer/Xcode/DerivedData/Runner-fwejzcrpyvwbzidiwwpcxlekybsf/Build/Products/Debug-iphonesimulator/BSGridCollectionViewLayout/BSGridCollectionViewLayout.swiftmodule/x86_64.swiftmodule

**Comment by mikaoj** [comment]
Give 2.10.3 a try. Bumped swift version in the podspec to 5.1

**Comment by robert4381** [comment]
Similar error with 2.10.3

/Users/ralmeida/Proyectos/iubo/source_app/Carthage/Checkouts/BSImagePicker/Sources/Controller/PhotosViewController.swift:25:8: error: module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/ralmeida/Proyectos/iubo/source_app/Carthage/Checkouts/BSImagePicker/Frameworks/BSGridCollectionViewLayout.framework/Modules/BSGridCollectionViewLayout.swiftmodule/arm64.swiftmodule
import BSGridCollectionViewLayout

**Comment by mikaoj** [comment]
Oh you are using carthage? Then bumping swift version in the podspec doesn't help you.

Try forcing a rebuild with carthage and make sure xcode-select points to Xcode 11 and not 10 if you have both on your computer.
```
carthage build --platform iOS
```

**Comment by robert4381** [comment]
I am using carthage + Xcode11.  

Removed Carthage directory. Tried with this options:

carthage build --platform iOS 
carthage update --platform iOS --no-use-binaries
carthage update --platform iOS 

But still same error on BSGridCollectionViewLayout   :(

**Comment by mikaoj** [comment]
Just to make sure...what does xcodebuild -version and swift --version say?

**Comment by robert4381** [comment]
➜ ~ xcodebuild -version
Xcode 11.0
Build version 11A420a

➜ ~ xcrun swift -version
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
Target: x86_64-apple-darwin18.7.0

**Comment by robert4381** [comment]
The problem is that BSGridCollectionViewLayout.framework is compiled with 5.0 & BSImagePicker linked with this compiled version. 
 
BSGridCollectionViewLayout compiles flawlessly.
BSImageView compiles flawlessly.
BSImagePicker compiles ok but links with error because is linked with the framework that is included in checkout. Not with the checkout version that Carthage downloads.

**Comment by mikaoj** [comment]
Fix it and make a pull request if you have the time

**Comment by robert4381** [comment]
Made pull request but CI failed. 

CI is using Xcode 10.2 but 11 is required to pass CI.

**Comment by robert4381** [comment]
Pull request done :)

**Comment by EHBradford** [comment]
My situation appears different from robert4381's.  I am using a Flutter library called multi_image_picker which depends upon this library.  

Given I know very little about Xcode I am not exactly sure what the nature of the problem is here.   Is it that my environment is attempting to use the wrong version of this library?  That is what it appears to be based upon my tiny bit of understanding. 

I have used a lot of compilers/linkers in the past, just haven't done it in a long time, and I am not familiar with Apple terminology.  

If my environment is utilizing the wrong library, should I be approaching you for help in determining the correct fix, or should I be approaching the multi_image_picker developers?

**Comment by mikaoj** [comment]
They at least seem to be somewhat related, lets see if @robert4381  pr fixes your issue as well.
If not I'll have to look into how flutter works and manages dependencies.

The 3.0 version I'm working on wont have this issue as I've integrated all dependencies directly into the source code. Got tired of always having to manage different package managers doing things differently.

**Comment by robert4381** [comment]
if Flutter uses Carthage then is almost sure that this fix will works with Flutter.

**Comment by EHBradford** [comment]
Would you mind trying to answer my question?   It would help me understand the problem here.  

 Is it that my environment is attempting to use the wrong version of this library?

**Comment by mikaoj** [comment]
I have no idea how flutter works.

No the problem is that there are frameworks bundled in this repo that have been built with swift 5.0.
They shouldn't really be used but be resolved and built by the dependency manager of you choice.
@robert4381 have a PR which I think fixes that, but I haven't had the time to look at it yet.

I did a quickfix for now, try using 2.10.4 - and I'll have a look at @robert4381 fix when I have time.

**Comment by EHBradford** [comment]
Thank You, 

So much for the help.  I appreciate your time looking into this matter.  

I definitely do not want you to figure out Flutter.  

I think I am going to just have to give up.  I simply don't have time to figure this out.  

Once again, thank you.

**Comment by Sh1d0w** [comment]
@EHBradford can you just change your Swift version to 5.0 ? I am running latest Xcode and the example app in the multi_image_picker repository compiles with no errors? Can you provide example repo where I can reproduce the error so I can help you?

**Comment by mikaoj** [comment]
Did you try 2.10.4?
