### ISSUE TITLE
Preselected images are not displayed as selected

### ISSUE THREAD

**Issue by sipi1020** [mikaoj/BSImagePicker#240]
I downloaded the latest example project and noticed that the "Image picker with selected assets" button opens the image picker but non of the images are displayed as selected. In the finish callback I have all the preselected assets and in the right corner of the picker, the number of preselected images are shown. ("Done(688)"). But I don't see any number or tick icon on any of the images.
I could reproduce the issue on Simulator and on real devices (iPhone SE and iPhone 11) as well.

**Comment by mikaoj** [comment]
Cool. It's pretty easy to fix. The issue is that the example is initializing and setting a AssetStore on the image picker.
While other parts of the picker (AssetsViewController) assumed that it wouldn't change and are using the initial AssetStore that the image picker created itself.
So we need to make sure that the entire image picker always is referring to the same AssetStore.

This is a great issue for someone to get started on.
How about you give it a go @sipi1020 ? :)
