### ISSUE TITLE
Xcode 12 different definitions in different modules issue.

### ISSUE THREAD

**Issue by dksqnswlwhr** [mikaoj/BSImagePicker#301]
When user using BSImagePicker and  using same name class ( Settings ). 
Can't build on Xcode 12. and Build error display ( different definitions in different modules  ). 
It is Objc header conflict issue. and I already create pull request. 

related thread : [https://developer.apple.com/forums/thread/658012](url)
and pull request : [https://github.com/mikaoj/BSImagePicker/pull/300](url)

**Comment by primeviltom** [comment]
Hi there,

I too am having this issue, since updating to xCode 12. None of the steps on the apple developer forums seem to work for me (deleting derived data, cleaning and rebooting etc.). Is there a fix for this yet? 

My specific build-time error is:

`'ImagePickerController' has different definitions in different modules; first difference is definition in module 'BSImagePicker.Swift' found super class with type 'UINavigationController'`

Thanks!

**Comment by dksqnswlwhr** [comment]
> Hi there,
> 
> I too am having this issue, since updating to xCode 12. None of the steps on the apple developer forums seem to work for me (deleting derived data, cleaning and rebooting etc.). Is there a fix for this yet?
> 
> My specific build-time error is:
> 
> `'ImagePickerController' has different definitions in different modules; first difference is definition in module 'BSImagePicker.Swift' found super class with type 'UINavigationController'`
> 
> Thanks!


it's already fixed. 
update your pods 
and checkout this [https://github.com/mikaoj/BSImagePicker/pull/300](url)

**Comment by giuliosantabarbara** [comment]
Hi,

I still have this issue, with Xcode 12.3 and v.3.3.1

The build-time error is the same as the previous post:

`'ImagePickerController' has different definitions in different modules; first difference is definition in module 'BSImagePicker.Swift' found super class with type 'UINavigationController'`
