### ISSUE TITLE
Use Image Picker Multiple Time

### ISSUE THREAD

**Issue by SohaibSiddique** [mikaoj/BSImagePicker#316]
Hello, 

I'm using this picker view and it's very good and ok for me, I have a question can I declare picker view globally and use multiple times in my app?

**Comment by mikaoj** [comment]
> I have a question can I declare picker view globally and use multiple times in my app

By the time it took for you to create this issue and ask that question you could have tried it and see if there are any issues. 😄 

1. Yes you _can_. It will probably 'remember' what was last picked if you do.
2. And if you don't want it to 'remember' what was last picked why would you want a 'global' picker instead of creating a new one when it is needed? What is the use case?

**Comment by mikaoj** [comment]
Closing. Feel free to reopen if you have noticed any issues.
